/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_marakana_android_lib_log_LibLog */

#ifndef _Included_com_marakana_android_lib_log_LibLog
#define _Included_com_marakana_android_lib_log_LibLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    libInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_android_lib_log_LibLog_libInit
  (JNIEnv *, jclass);

/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_android_lib_log_LibLog_init
  (JNIEnv *, jobject);

/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_android_lib_log_LibLog_close
  (JNIEnv *, jobject);

/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    flushLog
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_marakana_android_lib_log_LibLog_flushLog
  (JNIEnv *, jobject);

/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    getTotalLogSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_lib_log_LibLog_getTotalLogSize
  (JNIEnv *, jobject);

/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    getUsedLogSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_marakana_android_lib_log_LibLog_getUsedLogSize
  (JNIEnv *, jobject);

/*
 * Class:     com_marakana_android_lib_log_LibLog
 * Method:    waitForLogData
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_marakana_android_lib_log_LibLog_waitForLogData
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
