/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fabonaccinative_FabLib */

#ifndef _Included_com_example_fabonaccinative_FabLib
#define _Included_com_example_fabonaccinative_FabLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fabonaccinative_FabLib
 * Method:    fibNR
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fabonaccinative_FabLib_fibNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_example_fabonaccinative_FabLib
 * Method:    fibNI
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_example_fabonaccinative_FabLib_fibNI
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
